/**
 * Labels generated by this server (office titles, header labels, comparison
 * headings). Liturgical content itself is never translated — it stays in the
 * prayer book's language. The label locale follows the office/book language,
 * with ESTEVAO_LANGUAGE (or the tool's language param) as fallback.
 */

export type Locale = "pt" | "en" | "es";

export interface Labels {
  offices: Record<string, string>;
  season: string;
  color: string;
  prayerBook: string;
  celebration: string;
  readings: string;
  comparison: string;
  unavailable: string;
}

const LABELS: Record<Locale, Labels> = {
  pt: {
    offices: {
      morning: "Oração da Manhã",
      midday: "Oração do Meio-Dia",
      evening: "Oração da Tarde",
      compline: "Completas",
      late_evening: "Oração da Noite",
    },
    season: "Tempo",
    color: "Cor",
    prayerBook: "Livro de Oração",
    celebration: "Celebração",
    readings: "Leituras",
    comparison: "Comparação",
    unavailable: "Indisponível",
  },
  en: {
    offices: {
      morning: "Morning Prayer",
      midday: "Midday Prayer",
      evening: "Evening Prayer",
      compline: "Compline",
      late_evening: "Late Evening Prayer",
    },
    season: "Season",
    color: "Color",
    prayerBook: "Prayer book",
    celebration: "Celebration",
    readings: "Readings",
    comparison: "Comparison",
    unavailable: "Unavailable",
  },
  es: {
    offices: {
      morning: "Oración Matutina",
      midday: "Oración del Mediodía",
      evening: "Oración Vespertina",
      compline: "Completas",
      late_evening: "Oración de la Noche",
    },
    season: "Tiempo",
    color: "Color",
    prayerBook: "Libro de Oración",
    celebration: "Celebración",
    readings: "Lecturas",
    comparison: "Comparación",
    unavailable: "No disponible",
  },
};

/** Resolve "pt-BR" / "en" / "es-419" / undefined to a supported locale. */
export function resolveLocale(...candidates: Array<string | undefined>): Locale {
  for (const candidate of candidates) {
    const base = candidate?.trim().toLowerCase().split(/[-_]/)[0];
    if (base === "pt" || base === "en" || base === "es") return base;
  }
  return "en";
}

export function labels(locale: Locale): Labels {
  return LABELS[locale];
}
